version: '3.7'
#se definen los contenedores
services:
  nginx_laravel:
    image: nginx:stable-alpine
    container_name: nginx_laravel
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_laravel
      - mysql_laravel
    networks:
      - laravel_group

  mysql_laravel:
    image: mysql:8.0
    container_name: mysql_laravel
    restart: always
    environment:
      MYSQL_DATABASE: laravel-prueba
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 33061:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel_group

  php_laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_laravel
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
    networks:
      - laravel_group

networks:
  laravel_group:
